name: Update AUR

on:
  push:
    tags:
      - "v*"

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish AUR package
        uses: 20137/aurpublish@v1
        with:
          pkgname: desktopify-lite
          pkgbuild: ./packaging/aur/desktopify-lite/PKGBUILD
          commit_username: kainekillian
          commit_email: kainekillian@proton.me
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to ${{ github.ref_name }}"
