name: Update AUR

on:
  push:
    tags:
      - "v*"

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH Keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}

      - name: Publish to AUR
        run: |
          # Добавляем AUR в известные хосты
          ssh-keyscan -t ed25519 aur.archlinux.org >> ~/.ssh/known_hosts

          git config --global user.name "kaine-killian"
          git config --global user.email "kaine-killian@users.noreply.github.com"

          # Клонируем через SSH (ssh-agent сам подсунет ключ)
          git clone ssh://aur@aur.archlinux.org/desktopify-lite.git /tmp/aur-repo

          cp ./packaging/aur/desktopify-lite/PKGBUILD /tmp/aur-repo/
          cp ./packaging/aur/desktopify-lite/.SRCINFO /tmp/aur-repo/

          cd /tmp/aur-repo
          git add PKGBUILD .SRCINFO
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update to ${GITHUB_REF_NAME}"
            git push origin master
          fi
